//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.IssueR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Documents = new HashSet<Document>();
            this.Issues = new HashSet<Issue>();
            this.ProjectMembers = new HashSet<ProjectMember>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
    }
}
