//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.IssueR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.Documents = new HashSet<Documents>();
            this.Employees = new HashSet<Employees>();
            this.Epics = new HashSet<Epics>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Epics> Epics { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
