//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELTE.IssueR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Employees = new HashSet<Employees>();
            this.Messages = new HashSet<Messages>();
            this.Messages1 = new HashSet<Messages>();
            this.UserImages = new HashSet<UserImages>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Messages> Messages1 { get; set; }
        public virtual ICollection<UserImages> UserImages { get; set; }
    }
}
