//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Documents = new HashSet<Document>();
            this.Employees = new HashSet<Employee>();
            this.Epics = new HashSet<Epic>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Epic> Epics { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
